export const mentors_name = [
    ["---", "---"],
    ["กนกพล เพชรศรี", "ganogpol.p@ku.th"],
    ["นภารัตน์ เคนวิเศษ", "missnaparat.k@ku.th"],
    ["นนทกร จันทรโชติ", "nontakorn.ch@ku.th"],
    ["จักรดาว สุรินยา", "jakdow.s@ku.th"],
    ["วริศรา ลับกฤชคม", "varitsara.l@ku.th"],
    ["วริศรา จิตรธรรม", "varisara.ji@ku.th"],
    ["พีรณัฐ เผ่าผม", "peeranat.pha@ku.th"],
    ["ปิยพร ทองพอก", "piyaphon.th@ku.th"],
    ["ปาณิสรา ลิมปปวิช", "panisara.l@ku.th"],
    ["น.ส.กนกภรณ์ จันทร์เกิน", "kanokporn.c@ku.th"],
    ["ปริชานุช สว่างศรี", "parichanuch.s@ku.th"],
    ["ปรเมศวร์ ชูสุข", "poramet.chus@ku.th"],
    ["พิริยกร เขียวงามดี", "piriyakorn.kh@ku.th"],
    ["ณฐกฤษ มาคะคำ", "nathakrit.m@ku.th"],
    ["ชนิสรา ปทุมานนท์", "Chanisara.pat@ku.th"],
    ["อริสรา สัณฐิติบวร", "arisra.sa@ku.th"],
    ["จตุพันธุ์ มาลัย", "Jatupan.m@ku.th"],
    ["ภรภัทร์ สาบุตร", "Phorraphat.s@ku.th"],
    ["วรัญญู แย้มศรวล", "warunyu.y@ku.th"],
    ["ธนวรรธน์ จุฑาภิรมย์พร", "tanawat.chut@ku.th"],
    ["ภีมพงษ์ รอดวารี", "pheemmapong.r@ku.th"],
    ["รตามน เจริญรัตนคุณ", "ratamon.c@ku.th"],
    ["ณัฐพงษ์ ภักดีวิบูลย์", "nattapong@pak.ku.th"],
    ["ป้อมเดช ฟุ้ง", "pomdet.f@ku.th"],
    ["วริศรา อารยะวิไลพงศ์", "varissara.ar@ku.th"],
    ["สิรภพ ผลภักดี", "siraphob.ph@ku.th"],
    ["พศิน มากเจริญ", "pasin.ma@ku.th"],
    ["อภิวิชญ์ สายภู่", "aphiwit.sa@ku.th"],
    ["พศิน อาจิริยะ", "pasin.a@ku.th"],
    ["พัทธดนย์ ออกสุข", "pathadon.a@ku.th"],
    ["ศุภพล แดงประทีป", "suppapon.d@ku.th"],
    ["ฐิติพัฒน์ พาแพง", "thitiphat.pa@ku.th"],
    ["กิตติภูมิ สุทธิเลิศ", "kittipoom.su@ku.th"],
    ["วศุรัฐ สิงขรณ์", "wasurath.s@ku.th"],
    ["ภีศเดช สุราราช", "Pheesadet.s@ku.th"],
    ["ธนวัฒน์ สุขอัมพร", "thanawat.suk@ku.th"],
    ["ธนดล วรรัตนธรรม", "tanadon.wor@ku.th"],
    ["พีรทัศน์ วิจิตรจรัลรุ่ง", "peeratus.v@ku.th"],
    ["พศุตม์ ว่องไวกิจไพศาล", "pasuth.v@ku.th"],
    ["พันธ์นิพัทธ์ เทียนแก้ว", "phunnipath.t@ku.th"],
    ["ทิพากร ทิมอิ่ม", "thiphakorn.t@ku.th"],
    ["ณัฐกาญจน์ จันทร์งาม", "nattakan.c@ku.th"],
];

export const participants_name = [
    ["---", "---"],
    ["สุรศักดิ์ เพ็ชรโพธิ์", "surasak.pec@ku.th"],
    ["พศทรรศน์ จารุชิตโสภณ", "kazutokung59@gmail.com"],
    ["รวิภา พัฒนาภารดี", "rawipa.pa@ku.th"],
    ["คุณาสิน บรรพกาญจน์", "kunasin.bu@ku.th"],
    ["กัชชกร พันธุ์สะอาด", "sol.asc12@gmail.com"],
    ["เมธัส ศิลาโชติ", "matassil1207@gmail.com"],
    ["ณัฐวรรธน์ ลือเฟื่อง", "Nattawat.lu@ku.th"],
    ["พิชญุตม์ สุวรรณมุณี", "pitchayutm.s@ku.th"],
    ["ก้องภพ หิรัญรัตน์", "Kong pop.h@ku.th"],
    ["มาระดี เวหะชาติ", "maradeevehachart@gmail.com"],
    ["นภัสนันท์ ดาราเลิศกุลพัฒน์", "Napatsanan.da@ku.th"],
    ["ปาณิศา กุลธรรม", "panisa.v7@gmail.com"],
    ["สิริฉาย ข่มอาวุธ", "sirichaikluaymai@gmail.com"],
    ["ชัจจนันท์ สุนทรวิวัฒนาการ", "chajjanans@gmail.com"],
    ["อาทิตยา สุขปาน", "atittaya.suk@ku.th"],
    ["อักษรินทร์ กุลวโรตตมะ", "aksarin.k@ku.th"],
    ["จิณัฏฐ์ธิดา ตติยรัตน์", "jinathida.t@ku.th"],
    ["สวิตต์ ฉวีวงศ์", "sawitchaweewong@gmail.com"],
    ["พิชญาภา สันติวรนนท์", "Sonypitchayapa@gmail.com"],
    ["ชัญญานุช มณีศรี", "chanyanut.maneesri.5790@gmail.com"],
    ["ธารธิชล แซ่ตั้ง", "tharathichon.s@ku.th"],
    ["พิชญาภา เทียมตามณี", "pitchayapa.thi@ku.th"],
    ["แผ่นดิน จิตพิมลมาศ", "phanndin15499@gmail.com"],
    ["พีรณัฐ สุกใส", "peeranutsooksai@gmail.com"],
    ["ณฐภา ประสบผลเพิ่ม", "oowauii@gmail.com"],
    ["เกศินี แจ้งพูน", "kasinee.jan@ku.th"],
    ["ฐากูร เกตุทอง", "skysan2549@gmail.com"],
    ["สิรีธร ด้วงแป้น", "sireethon.d@ku.th"],
    ["ทักษพร แสนทวี", "taksapornsaentawee@gmail.com"],
    ["ซาร่า ราฮามัน", "sarah.r@ku.th"],
    ["วริศรา ปรุงเรณู", "warissara.pr@ku.th"],
    ["กัลยรักษ์ จิระธนาโสภณ", "kanyaruk.j@ku.th"],
    ["กชพร พรหมนุช", "kotchapornpromnuch@gmail.com"],
    ["ปาณิสรา ภู่หลักแก้ว", "Panisara204581.1@gmail.com"],
    ["จิรกิจ ปานศรี", "jirakit.pan@ku.th"],
    ["ณฐวัฒน์ อริยวงษ์พาณิช", "tiewkr1@gmail.com"],
    ["แสนสิริ แสนวงศ์", "Saensiri.s@ku.th"],
    ["ปรียาดา อินทรีย์วงศ์", "preeyadainseewong@gmail.com"],
    ["ปวิตรา ปริญญาปุณโณ", "pawittra.par@ku.th"],
    ["บวรรัตน์ ศรียุกต์", "bowornrat.sri@ku.th"],
    ["อัครวินท์ หลิว", "akarawin.w@ku.th"],
    ["นฤภร วจีปิยนันทานนท์", "naruporn.wa@ku.th"],
    ["กันตาธรณ์ ลัดดาหอม", "kantathorn.l@ku.th"],
    ["กฤติณัฎธ์ บุญประเสริฐ", "casetht@gmail.com"],
    ["ฟานูส หัสนีย์", "fanus.h@ku.th"],
    ["นันท์นภัส วิริยะวัฒนา", "nunnapat.wi@ku.th"],
    ["สิทธิพล ชุมสวัสดิ์วงศ์", "sittipol.ch@ku.th"],
    ["นาซินีน โปติล่ะ", "nasineen.p@ku.th"],
    ["นันท์นภัส ชาติศรีศักดิ์", "oneforatwo3@gmail.com"],
    ["ฟ้าใส วรศรีหิรัญ", "fasai.v@ku.th"],
    ["ปริธิดา ศรีเสสนาม", "parithida.s@ku.th"],
    ["ศุภิสสรา ประวัติงาม", "sp.prawatngam@gmail.com"],
    ["เดชาวิทย์ ชัชวาลย์", "tdechawit@gmail.com"],
    ["มัชฌิมา วรรณทอง", "muchshima.w@ku.th"],
    ["ชลิตา พรหมมา", "chalita230351@gmail.com"],
    ["พิพัฒพงศ์ เพ็งนาม", "pipatpong.ph@ku.th"],
    ["น.ส. พิชญธิดา โกศลวุฒิ", "phitchayathida.k@ku.th"],
    ["ฌาญวุฒิ พิษณุวัฒนศักดิ์", "chanywut.pi@ku.th"],
    ["จินตพล เตียวสุวรรณ์", "jintaphon.t@ku.th"],
    ["กมลภู พรมอ่อน", "atomkamolpoo@gmail.com"],
];

export const attendance = [
    "---",
    "Present",
    "Absent",
]

export const date_session = [
    "---",
    "29 August 2026 - Inspiration Startup & Design thinking",
    "30 August 2026 - Idea Validation Problem & Insight to solution and Value",
    "5 September 2026 - Prototyping and MVP Design",
    "6 September 2026 - Financial planning and coaching session",
    "12 September 2026 - How to Pitch",
    "13 September 2026 - Final Pitching Day",
]