export const mentors_name = [
    ["---", "---"],
    ["กนกพล เพชรศรี (---)", "ganogpol.p@ku.th"],
    ["นภารัตน์ เคนวิเศษ (---)", "missnaparat.k@ku.th"],
    ["นนทกร จันทรโชติ (คอปเตอร์ group 4)", "nontakorn.ch@ku.th"],
    ["จักรดาว สุรินยา (---)", "jakdow.s@ku.th"],
    ["วริศรา ลับกฤชคม (---)", "varitsara.l@ku.th"],
    ["วริศรา จิตรธรรม (เมอาย group 3)", "varisara.ji@ku.th"],
    ["พีรณัฐ เผ่าผม (---)", "peeranat.pha@ku.th"],
    ["ปิยพร ทองพอก (มิ้น group 1)", "piyaphon.th@ku.th"],
    ["ปาณิสรา ลิมปปวิช (เกน group 9)", "panisara.l@ku.th"],
    ["กนกภรณ์ จันทร์เกิน (เกน group 5)", "kanokporn.c@ku.th"],
    ["ปริชานุช สว่างศรี (เม group 8)", "parichanuch.s@ku.th"],
    ["ปรเมศวร์ ชูสุข (แบงค์ group 6)", "poramet.chus@ku.th"],
    ["พิริยกร เขียวงามดี (อาร์ม group 2)", "piriyakorn.kh@ku.th"],
    ["ณฐกฤษ มาคะคำ (ก้อง group 7)", "nathakrit.m@ku.th"],
    ["ชนิสรา ปทุมานนท์ (ฝ้าย group 4)", "Chanisara.pat@ku.th"],
    ["อริสรา สัณฐิติบวร (เเพนเค้ก group 10)", "arisra.sa@ku.th"],
    ["จตุพันธุ์ มาลัย (ไอซ์ group 11)", "Jatupan.m@ku.th"],
    ["ภรภัทร์ สาบุตร (ออม group 12)", "Phorraphat.s@ku.th"],
    ["วรัญญู แย้มศรวล (โชกุน group 1)", "warunyu.y@ku.th"],
    ["ธนวรรธน์ จุฑาภิรมย์พร (เจ็ต group 2)", "tanawat.chut@ku.th"],
    ["ภีมพงษ์ รอดวารี (ปราดเปรียว group 3)", "pheemmapong.r@ku.th"],
    ["รตามน เจริญรัตนคุณ (ต้า group 4)", "ratamon.c@ku.th"],
    ["ณัฐพงษ์ ภักดีวิบูลย์ (รัน group 5)", "nattapong@pak.ku.th"],
    ["ป้อมเดช ฟุง (คริส group 6)", "pomdet.f@ku.th"],
    ["วริศรา อารยะวิไลพงศ์ (โบนัส group 7)", "varissara.ar@ku.th"],
    ["สิรภพ ผลภักดี (พีม group 8)", "siraphob.ph@ku.th"],
    ["พศิน มากเจริญ (ปลื้ม group 5)", "pasin.ma@ku.th"],
    ["อภิวิชษ์ สายภู่ (ปั๊บ group 9)", "aphiwit.sa@ku.th"],
    ["พศิน อาจิริยะ (จูน group 2)", "pasin.a@ku.th"],
    ["พัทธดนย์ ออกสุข (โบอิ้ง group 4)", "pathadon.a@ku.th"],
    ["ศุภพล แดงประทีป (มอส group 8)", "suppapon.d@ku.th"],
    ["ฐิติพัฒน์ พาแพง (มาร์ค group 10)", "thitiphat.pa@ku.th"],
    ["กิตติภูมิ สุทธิเลิศ (ภูมิ group 6)", "kittipoom.su@ku.th"],
    ["วศุรัฐ สิงขรณ์ (ต้น group 11)", "wasurath.s@ku.th"],
    ["ภีศเดช สุราราช (เขต group 9)", "Pheesadet.s@ku.th"],
    ["ธนวัฒน์ สุขอัมพร (ฟร้อง group 1)", "thanawat.suk@ku.th"],
    ["ธนดล วรรัตนธรรม (เชียว group 12)", "tanadon.wor@ku.th"],
    ["พีรทัศน์ วิจิตรจรัลรุ่ง (เบสท์ group 3)", "peeratus.v@ku.th"],
    ["พศุตม์ ว่องไวกิจไพศาล (นะโม group 7)", "pasuth.v@ku.th"],
    ["พันธ์นิพัทธ์ เทียนแก้ว (Nice group 11)", "phunnipath.t@ku.th"],
    ["ทิพากร ทิมอิ่ม (ดรีม group 10)", "thiphakorn.t@ku.th"],
    ["ณัฐกาญจน์ จันทร์งาม (มิ่งขวัญ group 12)", "nattakan.c@ku.th"],
];

export const participants_name = [
    ["---", "---"],
    ["สุรศักดิ์ เพ็ชรโพธิ์ (กายเจ group 11)", "surasak.pec@ku.th"],
    ["พศทรรศน์ จารุชิตโสภณ (เต้ group 10)", "kazutokung59@gmail.com"],
    ["รวิภา พัฒนาภารดี (เกรซ group 2)", "rawipa.pa@ku.th"],
    ["คุณาสิน บรรพกาญจน์ (มาร์ค group 12)", "kunasin.bu@ku.th"],
    ["กัชชกร พันธุ์สะอาด (ซอล group 6)", "sol.asc12@gmail.com"],
    ["เมธัส ศิลาโชติ (อาร์ม group 3)", "matassil1207@gmail.com"],
    ["ณัฐวรรธน์ ลือเฟื่อง (เสธ group 4)", "Nattawat.lu@ku.th"],
    ["พิชญุตม์ สุวรรณมุณี (แพท group 8)", "pitchayutm.s@ku.th"],
    ["ก้องภพ หิรัญรัตน์ (นาว group 10)", "Kong pop.h@ku.th"],
    ["มาระดี เวหะชาติ (บัว group 6)", "maradeevehachart@gmail.com"],
    ["นภัสนันท์ ดาราเลิศกุลพัฒน์ (อั้ม group 9)", "Napatsanan.da@ku.th"],
    ["ปาณิศา กุลธรรม (ปิ๊ง group 3)", "panisa.v7@gmail.com"],
    ["สิริฉาย ข่มอาวุธ (กล้วยไม้ group 7)", "sirichaikluaymai@gmail.com"],
    ["ชัจจนันท์ สุนทรวิวัฒนาการ (กัปตัน group 4)", "chajjanans@gmail.com"],
    ["อาทิตยา สุขปาน (ขวัญ group 8)", "atittaya.suk@ku.th"],
    ["อักษรินทร์ กุลวโรตตมะ (อินดี้ group 9)", "aksarin.k@ku.th"],
    ["จิณัฏฐ์ธิดา ตติยรัตน์ (โบนัส group 12)", "jinathida.t@ku.th"],
    ["สวิตต์ ฉวีวงศ์ (ฟุค group 11)", "sawitchaweewong@gmail.com"],
    ["พิชญาภา สันติวรนนท์ (โซนี่ group 9)", "Sonypitchayapa@gmail.com"],
    ["ชัญญานุช มณีศรี (จีนส์ group 4)", "chanyanut.maneesri.5790@gmail.com"],
    ["ธารธิชล แซ่ตั้ง (พั้น group 10)", "tharathichon.s@ku.th"],
    ["พิชญาภา เทียมตามณี (มาย group 8)", "pitchayapa.thi@ku.th"],
    ["แผ่นดิน จิตพิมลมาศ (ไซแอม group 10)", "phanndin15499@gmail.com"],
    ["พีรณัฐ สุกใส (พีท group 11)", "peeranutsooksai@gmail.com"],
    ["ณฐภา ประสบผลเพิ่ม (แพร group 4)", "oowauii@gmail.com"],
    ["เกศินี แจ้งพูน (มายด์ group 5)", "kasinee.jan@ku.th"],
    ["ฐากูร เกตุทอง (สกาย group 1)", "skysan2549@gmail.com"],
    ["สิรีธร ด้วงแป้น (ซอฟท์ group 7)", "sireethon.d@ku.th"],
    ["ทักษพร แสนทวี (อันดา group 5)", "taksapornsaentawee@gmail.com"],
    ["ซาร่า ราฮามัน (ซาร่า group 1)", "sarah.r@ku.th"],
    ["วริศรา ปรุงเรณู (อิง group 10)", "warissara.pr@ku.th"],
    ["กัลยรักษ์ จิระธนาโสภณ (ไนซ์ group 8)", "kanyaruk.j@ku.th"],
    ["กชพร พรหมนุช (ม่อน group 7)", "kotchapornpromnuch@gmail.com"],
    ["ปาณิสรา ภู่หลักแก้ว (เกรท group 8)", "Panisara204581.1@gmail.com"],
    ["จิรกิจ ปานศรี (---)", "jirakit.pan@ku.th"],
    ["ณฐวัฒน์ อริยวงษ์พาณิช (ทิว group 12)", "tiewkr1@gmail.com"],
    ["แสนสิริ แสนวงศ์ (ไข่มุก group 3)", "Saensiri.s@ku.th"],
    ["ปรียาดา อินทรีย์วงศ์ (ปาล์มมี่ group 9)", "preeyadainseewong@gmail.com"],
    ["ปวิตรา ปริญญาปุณโณ (ต้นว่าน group 2)", "pawittra.par@ku.th"],
    ["บวรรัตน์ ศรียุกต์ (หยกศรี group 5)", "bowornrat.sri@ku.th"],
    ["อัครวินท์ หลิว (วินท์ group 6)", "akarawin.w@ku.th"],
    ["นฤภร วจีปิยนันทานนท์ (มิ้น group 1)", "naruporn.wa@ku.th"],
    ["กันตาธรณ์ ลัดดาหอม (ปริ้นท์ group 1)", "kantathorn.l@ku.th"],
    ["กฤติณัฎธ์ บุญประเสริฐ (เคส group 6)", "casetht@gmail.com"],
    ["ฟานูส หัสนีย์ (นอร์ท group 11)", "fanus.h@ku.th"],
    ["นันท์นภัส วิริยะวัฒนา (นัตตี้ group 2)", "nunnapat.wi@ku.th"],
    ["สิทธิพล ชุมสวัสดิ์วงศ์ (เซน group 12)", "sittipol.ch@ku.th"],
    ["นาซินีน โปติล่ะ (นีน group 3)", "nasineen.p@ku.th"],
    ["นันท์นภัส ชาติศรีศักดิ์ (มีนา group 5)", "oneforatwo3@gmail.com"],
    ["ฟ้าใส วรศรีหิรัญ (ฟ้าใส group 11)", "fasai.v@ku.th"],
    ["ปริธิดา ศรีเสสนาม (เค้ก group 5)", "parithida.s@ku.th"],
    ["ศุภิสสรา ประวัติงาม (มิ้น group 7)", "sp.prawatngam@gmail.com"],
    ["เดชาวิทย์ ชัชวาลย์ (ไตเติ้ล group 4)", "tdechawit@gmail.com"],
    ["มัชฌิมา วรรณทอง (ส้มโอ group 9)", "muchshima.w@ku.th"],
    ["ชลิตา พรหมมา (ออร์คิด group 12)", "chalita230351@gmail.com"],
    ["พิพัฒพงศ์ เพ็งนาม (โซดา group 6)", "pipatpong.ph@ku.th"],
    ["น.ส. พิชญธิดา โกศลวุฒิ (นุ่น group 1)", "phitchayathida.k@ku.th"],
    ["ฌาญวุฒิ พิษณุวัฒนศักดิ์ (นาย group 3)", "chanywut.pi@ku.th"],
    ["จินตพล เตียวสุวรรณ์ (บอนด์ group 7)", "jintaphon.t@ku.th"],
    ["กมลภู พรมอ่อน (อะตอม group 2)", "atomkamolpoo@gmail.com"],
];


export const attendance = [
    "---",
    "Present",
    "Absent",
]

export const date_session = [
    "---",
    "29 August 2026 - Inspiration Startup & Design thinking",
    "30 August 2026 - Idea Validation Problem & Insight to solution and Value",
    "5 September 2026 - Prototyping and MVP Design",
    "6 September 2026 - Financial planning and coaching session",
    "12 September 2026 - How to Pitch",
    "13 September 2026 - Final Pitching Day",
]