export const mentors_name = [
    ["---", "---"],
    ["กนกพล เพชรศรี (---)", "ganogpol.p@ku.th"],
    ["นภารัตน์ เคนวิเศษ (---)", "missnaparat.k@ku.th"],
    ["นนทกร จันทรโชติ (group 4)", "nontakorn.ch@ku.th"],
    ["จักรดาว สุรินยา (---)", "jakdow.s@ku.th"],
    ["วริศรา ลับกฤชคม (---)", "varitsara.l@ku.th"],
    ["วริศรา จิตรธรรม (group 3)", "varisara.ji@ku.th"],
    ["พีรณัฐ เผ่าผม (---)", "peeranat.pha@ku.th"],
    ["ปิยพร ทองพอก (group 1)", "piyaphon.th@ku.th"],
    ["ปาณิสรา ลิมปปวิช (group 9)", "panisara.l@ku.th"],
    ["น.ส.กนกภรณ์ จันทร์เกิน (group 5)", "kanokporn.c@ku.th"],
    ["ปริชานุช สว่างศรี (group 8)", "parichanuch.s@ku.th"],
    ["ปรเมศวร์ ชูสุข (group 6)", "poramet.chus@ku.th"],
    ["พิริยกร เขียวงามดี (group 2)", "piriyakorn.kh@ku.th"],
    ["ณฐกฤษ มาคะคำ (group 7)", "nathakrit.m@ku.th"],
    ["ชนิสรา ปทุมานนท์ (group 4)", "Chanisara.pat@ku.th"],
    ["อริสรา สัณฐิติบวร (group 10)", "arisra.sa@ku.th"],
    ["จตุพันธุ์ มาลัย (group 11)", "Jatupan.m@ku.th"],
    ["ภรภัทร์ สาบุตร (group 12)", "Phorraphat.s@ku.th"],
    ["วรัญญู แย้มศรวล (group 1)", "warunyu.y@ku.th"],
    ["ธนวรรธน์ จุฑาภิรมย์พร (group 2)", "tanawat.chut@ku.th"],
    ["ภีมพงษ์ รอดวารี (group 3)", "pheemmapong.r@ku.th"],
    ["รตามน เจริญรัตนคุณ (group 4)", "ratamon.c@ku.th"],
    ["ณัฐพงษ์ ภักดีวิบูลย์ (group 5)", "nattapong@pak.ku.th"],
    ["ป้อมเดช ฟุ้ง (group 6)", "pomdet.f@ku.th"],
    ["วริศรา อารยะวิไลพงศ์ (group 7)", "varissara.ar@ku.th"],
    ["สิรภพ ผลภักดี (group 8)", "siraphob.ph@ku.th"],
    ["พศิน มากเจริญ (group 5)", "pasin.ma@ku.th"],
    ["อภิวิชญ์ สายภู่ (group 9)", "aphiwit.sa@ku.th"],
    ["พศิน อาจิริยะ (group 2)", "pasin.a@ku.th"],
    ["พัทธดนย์ ออกสุข (group 4)", "pathadon.a@ku.th"],
    ["ศุภพล แดงประทีป (group 8)", "suppapon.d@ku.th"],
    ["ฐิติพัฒน์ พาแพง (group 10)", "thitiphat.pa@ku.th"],
    ["กิตติภูมิ สุทธิเลิศ (group 6)", "kittipoom.su@ku.th"],
    ["วศุรัฐ สิงขรณ์ (group 11)", "wasurath.s@ku.th"],
    ["ภีศเดช สุราราช (group 9)", "Pheesadet.s@ku.th"],
    ["ธนวัฒน์ สุขอัมพร (group 1)", "thanawat.suk@ku.th"],
    ["ธนดล วรรัตนธรรม (group 12)", "tanadon.wor@ku.th"],
    ["พีรทัศน์ วิจิตรจรัลรุ่ง (group 3)", "peeratus.v@ku.th"],
    ["พศุตม์ ว่องไวกิจไพศาล (group 7)", "pasuth.v@ku.th"],
    ["พันธ์นิพัทธ์ เทียนแก้ว (group 11)", "phunnipath.t@ku.th"],
    ["ทิพากร ทิมอิ่ม (group 10)", "thiphakorn.t@ku.th"],
    ["ณัฐกาญจน์ จันทร์งาม (group 12)", "nattakan.c@ku.th"],
];

export const participants_name = [
    ["---", "---"],
    ["สุรศักดิ์ เพ็ชรโพธิ์ (group 11)", "surasak.pec@ku.th"],
    ["พศทรรศน์ จารุชิตโสภณ (group 10)", "kazutokung59@gmail.com"],
    ["รวิภา พัฒนาภารดี (group 2)", "rawipa.pa@ku.th"],
    ["คุณาสิน บรรพกาญจน์ (group 12)", "kunasin.bu@ku.th"],
    ["กัชชกร พันธุ์สะอาด (group 6)", "sol.asc12@gmail.com"],
    ["เมธัส ศิลาโชติ (group 3)", "matassil1207@gmail.com"],
    ["ณัฐวรรธน์ ลือเฟื่อง (group 4)", "Nattawat.lu@ku.th"],
    ["พิชญุตม์ สุวรรณมุณี (group 8)", "pitchayutm.s@ku.th"],
    ["ก้องภพ หิรัญรัตน์ (group 10)", "Kong pop.h@ku.th"],
    ["มาระดี เวหะชาติ (group 6)", "maradeevehachart@gmail.com"],
    ["นภัสนันท์ ดาราเลิศกุลพัฒน์ (group 9)", "Napatsanan.da@ku.th"],
    ["ปาณิศา กุลธรรม (group 3)", "panisa.v7@gmail.com"],
    ["สิริฉาย ข่มอาวุธ (group 7)", "sirichaikluaymai@gmail.com"],
    ["ชัจจนันท์ สุนทรวิวัฒนาการ (group 4)", "chajjanans@gmail.com"],
    ["อาทิตยา สุขปาน (group 8)", "atittaya.suk@ku.th"],
    ["อักษรินทร์ กุลวโรตตมะ (group 9)", "aksarin.k@ku.th"],
    ["จิณัฏฐ์ธิดา ตติยรัตน์ (group 12)", "jinathida.t@ku.th"],
    ["สวิตต์ ฉวีวงศ์ (group 11)", "sawitchaweewong@gmail.com"],
    ["พิชญาภา สันติวรนนท์ (group 9)", "Sonypitchayapa@gmail.com"],
    ["ชัญญานุช มณีศรี (group 4)", "chanyanut.maneesri.5790@gmail.com"],
    ["ธารธิชล แซ่ตั้ง (group 10)", "tharathichon.s@ku.th"],
    ["พิชญาภา เทียมตามณี (group 8)", "pitchayapa.thi@ku.th"],
    ["แผ่นดิน จิตพิมลมาศ (group 10)", "phanndin15499@gmail.com"],
    ["พีรณัฐ สุกใส (group 11)", "peeranutsooksai@gmail.com"],
    ["ณฐภา ประสบผลเพิ่ม (group 4)", "oowauii@gmail.com"],
    ["เกศินี แจ้งพูน (group 5)", "kasinee.jan@ku.th"],
    ["ฐากูร เกตุทอง (group 1)", "skysan2549@gmail.com"],
    ["สิรีธร ด้วงแป้น (group 7)", "sireethon.d@ku.th"],
    ["ทักษพร แสนทวี (group 5)", "taksapornsaentawee@gmail.com"],
    ["ซาร่า ราฮามัน (group 1)", "sarah.r@ku.th"],
    ["วริศรา ปรุงเรณู (group 10)", "warissara.pr@ku.th"],
    ["กัลยรักษ์ จิระธนาโสภณ (group 8)", "kanyaruk.j@ku.th"],
    ["กชพร พรหมนุช (group 7)", "kotchapornpromnuch@gmail.com"],
    ["ปาณิสรา ภู่หลักแก้ว (group 8)", "Panisara204581.1@gmail.com"],
    ["จิรกิจ ปานศรี (---)", "jirakit.pan@ku.th"],
    ["ณฐวัฒน์ อริยวงษ์พาณิช (group 12)", "tiewkr1@gmail.com"],
    ["แสนสิริ แสนวงศ์ (group 3)", "Saensiri.s@ku.th"],
    ["ปรียาดา อินทรีย์วงศ์ (group 9)", "preeyadainseewong@gmail.com"],
    ["ปวิตรา ปริญญาปุณโณ (group 2)", "pawittra.par@ku.th"],
    ["บวรรัตน์ ศรียุกต์ (group 5)", "bowornrat.sri@ku.th"],
    ["อัครวินท์ หลิว (group 6)", "akarawin.w@ku.th"],
    ["นฤภร วจีปิยนันทานนท์ (group 1)", "naruporn.wa@ku.th"],
    ["กันตาธรณ์ ลัดดาหอม (group 1)", "kantathorn.l@ku.th"],
    ["กฤติณัฎธ์ บุญประเสริฐ (group 6)", "casetht@gmail.com"],
    ["ฟานูส หัสนีย์ (group 11)", "fanus.h@ku.th"],
    ["นันท์นภัส วิริยะวัฒนา (group 2)", "nunnapat.wi@ku.th"],
    ["สิทธิพล ชุมสวัสดิ์วงศ์ (group 12)", "sittipol.ch@ku.th"],
    ["นาซินีน โปติล่ะ (group 3)", "nasineen.p@ku.th"],
    ["นันท์นภัส ชาติศรีศักดิ์ (group 5)", "oneforatwo3@gmail.com"],
    ["ฟ้าใส วรศรีหิรัญ (group 11)", "fasai.v@ku.th"],
    ["ปริธิดา ศรีเสสนาม (group 5)", "parithida.s@ku.th"],
    ["ศุภิสสรา ประวัติงาม (group 7)", "sp.prawatngam@gmail.com"],
    ["เดชาวิทย์ ชัชวาลย์ (group 4)", "tdechawit@gmail.com"],
    ["มัชฌิมา วรรณทอง (group 9)", "muchshima.w@ku.th"],
    ["ชลิตา พรหมมา (group 12)", "chalita230351@gmail.com"],
    ["พิพัฒพงศ์ เพ็งนาม (group 6)", "pipatpong.ph@ku.th"],
    ["น.ส. พิชญธิดา โกศลวุฒิ (group 1)", "phitchayathida.k@ku.th"],
    ["ฌาญวุฒิ พิษณุวัฒนศักดิ์ (group 3)", "chanywut.pi@ku.th"],
    ["จินตพล เตียวสุวรรณ์ (group 7)", "jintaphon.t@ku.th"],
    ["กมลภู พรมอ่อน (group 2)", "atomkamolpoo@gmail.com"],
];

export const attendance = [
    "---",
    "Present",
    "Absent",
]

export const date_session = [
    "---",
    "29 August 2026 - Inspiration Startup & Design thinking",
    "30 August 2026 - Idea Validation Problem & Insight to solution and Value",
    "5 September 2026 - Prototyping and MVP Design",
    "6 September 2026 - Financial planning and coaching session",
    "12 September 2026 - How to Pitch",
    "13 September 2026 - Final Pitching Day",
]